import { ChangeRequest } from './types';

export const DEFAULT_LEAD = {
  name: 'Sarah Chen',
  role: 'Lead PM / Partner',
  avatarUrl: '/assets/04_headshot_pm.png',
};

export const INITIAL_CHANGE_REQUESTS: ChangeRequest[] = [
  {
    id: 'CR-1042',
    client: 'Acme Corp',
    clientLogo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA3XyCHjDZBkS9oXGbtw6TOz3rP-CS6Py0ophkwWVbgxdEQJVw8L4Z1fYmAJjtl-c0JzcOeffpSWBCw5mUNeBFlmsC9iZii08dzT1olXggLvWwPrZbdpLAlZ2pxAVGvLspXDTRiO63wBWlrRbtn7i7eKmO2gGJ81WshI7shja-34C-jhkpihlXYOjp7XqCd69oK4DadFiVBktH24EtEUAkdyieMalPOs1i1aGRHOi_7lHwuC-5ZpxNk2g',
    project: 'Enterprise Billing & Invoicing',
    title: 'Enterprise Tiered Pricing & Pro-rated Invoicing',
    description: 'Automated subscription upgrades, seat-tier threshold overrides, and proration credit handling.',
    rawQuote: '“We signed Pilot Alpha today. We desperately need mid-cycle billing proration and seat tiers live by Sprint 38 to invoice them without manual calculation.”',
    channel: 'Portal',
    channelSource: 'Client Portal',
    urgency: 'High',
    status: 'pending',
    estimatedHours: 24,
    hourlyRate: 150,
    estimatedCost: 3600,
    targetSprint: 'Sprint 38 (Q3 Release)',
    targetTurnaroundDays: 5,
    createdAt: '2025-05-18T16:42:00Z',
    updatedAt: '2025-05-18T16:42:00Z',
    clientContact: {
      name: 'Mark Jensen',
      email: 'mark@acme.corp',
      role: 'VP Product',
      avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCKpyD6fJddlQtoVbQZUxzvIt0fR5WUbkyyMgT_MPTNantddxWHN23Dc-Zm5Yp2yQt-58oA004A4tiWMvtBXy40u0WSUrPGl-RWURkyyiPhKiunp0S9CjsaWZiGiT-o_qzVSssPeJczkMUJ9HhG7P_-8lFq8uj-DwtjqXYMo8XU2ubbU6M_Nkr-2RybzZj2muQ_MgD1O0BuYamLKi6ycZAwWCFU-kLuWncNzGHi-GEcyljM-Is9Ev4gvw',
    },
    assignedLead: DEFAULT_LEAD,
    deliverables: [
      {
        id: 'del-1',
        title: 'Database Schema & Migration',
        description: 'Postgres enum additions for tiered volume breakpoints and audit columns.',
        hours: 4,
        category: 'Database / API',
      },
      {
        id: 'del-2',
        title: 'Stripe Billing Proration Webhook Engine',
        description: 'Sync customer invoice lines on subscription change events and calculate balance credits.',
        hours: 8,
        category: 'Backend',
      },
      {
        id: 'del-3',
        title: 'Admin Customer Portal Seat Adjustment Interface',
        description: 'React dashboard dialog allowing billing admins to view pro-rated delta before confirmation.',
        hours: 8,
        category: 'Frontend',
      },
      {
        id: 'del-4',
        title: 'Automated Invoice PDF Credit Recalculation',
        description: 'Adjust headless PDF generator to display credit line items and net payable sum.',
        hours: 4,
        category: 'QA & DevOps',
      },
    ],
    exclusions: [
      'Multi-currency exchange rate hedging',
      'Retroactive re-billing of historical cycles prior to Q2',
      'Direct ERP / QuickBooks live automated sync (separate CR-1055 scope)',
    ],
    approvalToken: 'tok_acme_89f2a',
  },
  {
    id: 'CR-1043',
    client: 'Veloce Health',
    project: 'Patient Intake Portal',
    title: 'HIPAA-Compliant Document Upload & Virus Scanning',
    description: 'Direct S3 pre-signed upload with ClamAV virus scanning pipeline and automated encrypted archiving.',
    rawQuote: '“Our compliance auditor flagged patient PDF uploads. We need quarantine scanning before files touch the database.”',
    channel: 'Portal',
    channelSource: 'Client Portal',
    urgency: 'Critical',
    status: 'approved',
    estimatedHours: 32,
    hourlyRate: 150,
    estimatedCost: 4800,
    targetSprint: 'Sprint 37',
    targetTurnaroundDays: 6,
    createdAt: '2025-05-16T11:20:00Z',
    updatedAt: '2025-05-17T09:15:00Z',
    clientContact: {
      name: 'Dr. Elena Rostova',
      email: 'e.rostova@veloce.io',
      role: 'Chief Medical Officer',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    },
    assignedLead: DEFAULT_LEAD,
    deliverables: [
      {
        id: 'del-201',
        title: 'AWS S3 Quarantine Bucket Setup',
        description: 'Isolated pre-scan bucket with Lambda trigger for instant ClamAV scan.',
        hours: 8,
        category: 'QA & DevOps',
      },
      {
        id: 'del-202',
        title: 'Async Scan Notification & UI Progress Bar',
        description: 'Websocket events reporting file scan verification to patient UI.',
        hours: 12,
        category: 'Frontend',
      },
      {
        id: 'del-203',
        title: 'Audit Logging & Encryption At Rest',
        description: 'KMS-managed 256-bit encryption and immutable HIPAA audit trail entries.',
        hours: 12,
        category: 'Backend',
      },
    ],
    exclusions: ['Legacy document migration from old server', 'OCR text extraction'],
    approvalToken: 'tok_veloce_34bc9',
    approvalDetails: {
      approvedAt: '2025-05-17T09:15:00Z',
      approvedBy: 'Dr. Elena Rostova',
      confirmationCode: 'CF-9712',
    },
  },
  {
    id: 'CR-1044',
    client: 'HyperScale Inc',
    project: 'SaaS Analytics Dashboard',
    title: 'Custom Metric Formula Builder & CSV Exporter',
    description: 'Allow team managers to define computed KPIs (e.g. LTV / CAC ratio) and export filtered aggregates.',
    rawQuote: '“Finance needs to compute custom weighted ratios directly in the table instead of dumping into Excel every morning.”',
    channel: 'Portal',
    channelSource: 'Client Portal',
    urgency: 'Medium',
    status: 'in_progress',
    estimatedHours: 20,
    hourlyRate: 150,
    estimatedCost: 3000,
    targetSprint: 'Sprint 38',
    targetTurnaroundDays: 4,
    createdAt: '2025-05-17T14:30:00Z',
    updatedAt: '2025-05-18T10:00:00Z',
    clientContact: {
      name: 'Julian Hayes',
      email: 'julian@hyperscale.co',
      role: 'Head of Growth',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    },
    assignedLead: DEFAULT_LEAD,
    deliverables: [
      {
        id: 'del-301',
        title: 'Math Parser & Safe Expression Evaluator',
        description: 'Server-side sandboxed formula evaluation with syntax verification.',
        hours: 6,
        category: 'Backend',
      },
      {
        id: 'del-302',
        title: 'Formula Input Modal & Autocomplete',
        description: 'UI input with column tag autocomplete and live syntax preview.',
        hours: 8,
        category: 'Frontend',
      },
      {
        id: 'del-303',
        title: 'Streaming CSV & XLSX Export Worker',
        description: 'Background worker to stream large datasets without memory timeouts.',
        hours: 6,
        category: 'QA & DevOps',
      },
    ],
    exclusions: ['Predictive ML modeling', 'SQL raw injection support'],
    approvalToken: 'tok_hyper_671fa',
    approvalDetails: {
      approvedAt: '2025-05-18T10:00:00Z',
      approvedBy: 'Julian Hayes',
      confirmationCode: 'CF-9788',
    },
  },
  {
    id: 'CR-1045',
    client: 'Nexus Labs',
    project: 'Robotics Fleet Commander',
    title: 'Live Telemetry Map Clustering & Latency Thresholds',
    description: 'Mapbox WebGL clustering for 5,000+ autonomous delivery drones with ping anomaly highlighting.',
    rawQuote: '“Map is lagging with over 2,000 units on screen. We need GeoJSON clustering and latency color-coding ASAP.”',
    channel: 'Portal',
    channelSource: 'Client Portal',
    urgency: 'High',
    status: 'pending',
    estimatedHours: 28,
    hourlyRate: 160,
    estimatedCost: 4480,
    targetSprint: 'Sprint 39',
    targetTurnaroundDays: 5,
    createdAt: '2025-05-18T08:15:00Z',
    updatedAt: '2025-05-18T08:15:00Z',
    clientContact: {
      name: 'Siddharth Patel',
      email: 'spatel@nexuslabs.tech',
      role: 'VP Engineering',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    },
    assignedLead: DEFAULT_LEAD,
    deliverables: [
      {
        id: 'del-401',
        title: 'Supercluster GeoJSON Optimization',
        description: 'Offload client-side point clustering to Web Workers with dynamic zoom radius.',
        hours: 10,
        category: 'Frontend',
      },
      {
        id: 'del-402',
        title: 'Telemetry WebSocket Compression',
        description: 'Implement Protocol Buffers over WebSocket for 80% payload size reduction.',
        hours: 12,
        category: 'Backend',
      },
      {
        id: 'del-403',
        title: 'Latency Ping Anomaly Alerts',
        description: 'Visual pulsating ping indicators when drone packet loss exceeds 250ms.',
        hours: 6,
        category: 'Frontend',
      },
    ],
    exclusions: ['3D Lidar point cloud rendering', 'Hardware firmware changes'],
    approvalToken: 'tok_nexus_910dd',
  },
  {
    id: 'CR-1046',
    client: 'Luminary Media',
    project: 'Audio Streaming App',
    title: 'Dolby Atmos Spatial Audio Toggle & Equalizer Presets',
    description: 'Integrate native spatial playback selector and customizable 10-band equalizer for premium subscribers.',
    rawQuote: '“Dolby partnership was finalized yesterday. Premium listeners must have spatial audio toggle on mobile and web.”',
    channel: 'Portal',
    channelSource: 'Client Portal',
    urgency: 'Medium',
    status: 'draft',
    estimatedHours: 18,
    hourlyRate: 150,
    estimatedCost: 2700,
    targetSprint: 'Sprint 39',
    targetTurnaroundDays: 4,
    createdAt: '2025-05-19T09:40:00Z',
    updatedAt: '2025-05-19T09:40:00Z',
    clientContact: {
      name: 'Chloe Davenport',
      email: 'chloe@luminary.fm',
      role: 'Product Lead, Audio',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    },
    assignedLead: DEFAULT_LEAD,
    deliverables: [
      {
        id: 'del-501',
        title: 'Web Audio API Node Routing',
        description: 'Set up BiquadFilterNodes for 10-band frequency tuning with flat response baseline.',
        hours: 8,
        category: 'Frontend',
      },
      {
        id: 'del-502',
        title: 'Dolby Stream Manifest Decoder',
        description: 'Parse HLS audio tracks to detect binaural Atmos multichannel feeds.',
        hours: 6,
        category: 'Backend',
      },
      {
        id: 'del-503',
        title: 'Audio Equalizer UI & Sliders',
        description: 'Sleek dark-mode equalizer presets (Bass Boost, Vocal, Club, Custom).',
        hours: 4,
        category: 'Frontend',
      },
    ],
    exclusions: ['Hardware DTS:X licensing', 'Offline spatial transcoding'],
    approvalToken: 'tok_luminary_44ae1',
  },
  {
    id: 'CR-1047',
    client: 'Strata Logistics',
    project: 'Driver Dispatch Mobile App',
    title: 'Offline Proof-of-Delivery Signature & Photo Sync',
    description: 'IndexedDB offline queue allowing drivers in dead zones to capture customer signatures and photo proof.',
    rawQuote: '“Drivers in rural Texas keep losing deliveries because the app locks up without cellular connectivity.”',
    channel: 'Portal',
    channelSource: 'Client Portal',
    urgency: 'High',
    status: 'approved',
    estimatedHours: 26,
    hourlyRate: 150,
    estimatedCost: 3900,
    targetSprint: 'Sprint 37',
    targetTurnaroundDays: 5,
    createdAt: '2025-05-15T15:00:00Z',
    updatedAt: '2025-05-16T17:20:00Z',
    clientContact: {
      name: 'Marcus Brody',
      email: 'mbrody@stratalogistics.com',
      role: 'VP Operations',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    },
    assignedLead: DEFAULT_LEAD,
    deliverables: [
      {
        id: 'del-601',
        title: 'Canvas Signature Capture Pad',
        description: 'Smooth vector path signature capture with high DPI support and stroke smoothing.',
        hours: 6,
        category: 'Frontend',
      },
      {
        id: 'del-602',
        title: 'Offline IndexedDB Sync Engine',
        description: 'Store signature base64 & compressed photos locally, auto-retry on reconnect.',
        hours: 12,
        category: 'Frontend',
      },
      {
        id: 'del-603',
        title: 'Server Idempotency & Verification Endpoint',
        description: 'Prevent duplicate delivery submissions and generate signed timestamp receipt.',
        hours: 8,
        category: 'Backend',
      },
    ],
    exclusions: ['Satellite hardware GPS tracking', 'Physical printer Bluetooth pairing'],
    approvalToken: 'tok_strata_7890f',
    approvalDetails: {
      approvedAt: '2025-05-16T17:20:00Z',
      approvedBy: 'Marcus Brody',
      confirmationCode: 'CF-9654',
    },
  },
  {
    id: 'CR-1048',
    client: 'Acme Corp',
    project: 'Customer CRM',
    title: 'Salesforce Two-Way Opportunity Contact Sync',
    description: 'Bi-directional webhook syncing newly qualified leads between Acme CRM and Salesforce Enterprise.',
    rawQuote: '“Sales reps are double-entering lead data into both systems. We need seamless webhook sync.”',
    channel: 'Portal',
    channelSource: 'Client Portal',
    urgency: 'Medium',
    status: 'pending',
    estimatedHours: 22,
    hourlyRate: 150,
    estimatedCost: 3300,
    targetSprint: 'Sprint 38',
    targetTurnaroundDays: 4,
    createdAt: '2025-05-17T18:00:00Z',
    updatedAt: '2025-05-17T18:00:00Z',
    clientContact: {
      name: 'Mark Jensen',
      email: 'mark@acme.corp',
      role: 'VP Product',
      avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCKpyD6fJddlQtoVbQZUxzvIt0fR5WUbkyyMgT_MPTNantddxWHN23Dc-Zm5Yp2yQt-58oA004A4tiWMvtBXy40u0WSUrPGl-RWURkyyiPhKiunp0S9CjsaWZiGiT-o_qzVSssPeJczkMUJ9HhG7P_-8lFq8uj-DwtjqXYMo8XU2ubbU6M_Nkr-2RybzZj2muQ_MgD1O0BuYamLKi6ycZAwWCFU-kLuWncNzGHi-GEcyljM-Is9Ev4gvw',
    },
    assignedLead: DEFAULT_LEAD,
    deliverables: [
      {
        id: 'del-701',
        title: 'Salesforce OAuth2 App & Refresh Token Flow',
        description: 'Secure token storage in encrypted vault and auto-refresh credentials.',
        hours: 6,
        category: 'Backend',
      },
      {
        id: 'del-702',
        title: 'Field Mapping Config Table & Webhook Queue',
        description: 'BullMQ redis queue handling rate limiting and retry backoff.',
        hours: 10,
        category: 'Backend',
      },
      {
        id: 'del-703',
        title: 'Sync Conflict Resolution UI',
        description: 'Admin view highlighting schema discrepancies and field collisions.',
        hours: 6,
        category: 'Frontend',
      },
    ],
    exclusions: ['HubSpot or Marketo legacy integrations', 'Data cleansing of dirty contacts'],
    approvalToken: 'tok_acme_1109a',
  },
  {
    id: 'CR-1049',
    client: 'Beacon Retail',
    project: 'E-Commerce Storefront',
    title: 'Apple Pay & Google Pay One-Click Checkout Sheet',
    description: 'Direct cart-skipping express checkout buttons on product detail pages via Stripe Payment Request API.',
    rawQuote: '“Mobile bounce rates on checkout step 1 are over 60%. We need 1-tap Apple Pay directly on product pages.”',
    channel: 'Portal',
    channelSource: 'Client Portal',
    urgency: 'Critical',
    status: 'declined',
    estimatedHours: 16,
    hourlyRate: 150,
    estimatedCost: 2400,
    targetSprint: 'Sprint 38',
    targetTurnaroundDays: 3,
    createdAt: '2025-05-14T12:10:00Z',
    updatedAt: '2025-05-14T12:10:00Z',
    clientContact: {
      name: 'Samantha Vance',
      email: 'samantha@beaconretail.com',
      role: 'Head of E-Commerce',
      avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    },
    assignedLead: DEFAULT_LEAD,
    deliverables: [
      {
        id: 'del-801',
        title: 'Stripe Payment Request Button Integration',
        description: 'Native Apple Pay and Google Pay sheet triggers with address autofill.',
        hours: 8,
        category: 'Frontend',
      },
      {
        id: 'del-802',
        title: 'Instant Tax & Shipping Rates API Calculation',
        description: 'Calculate live shipping rates on payment request sheet postal code change.',
        hours: 8,
        category: 'Backend',
      },
    ],
    exclusions: ['Klarna BNPL integration', 'Custom gift card balance application'],
    approvalToken: 'tok_beacon_5521b',
    approvalDetails: {
      feedbackNotes: 'Client postponed to Q4 budget cycle due to merchant bank contract renegotiation.',
    },
  },
  {
    id: 'CR-1050',
    client: 'AeroPulse Avionics',
    project: 'Flight Deck Telemetry Web App',
    title: 'FAA Audit Log Export & Cryptographic Signature',
    description: 'Automated generation of SHA-256 tamper-evident flight log packages for compliance inspection.',
    rawQuote: '“Our upcoming FAA inspection requires verifiable digital signatures on all pilot checklist logs.”',
    channel: 'Portal',
    channelSource: 'Client Portal',
    urgency: 'High',
    status: 'completed',
    estimatedHours: 24,
    hourlyRate: 175,
    estimatedCost: 4200,
    targetSprint: 'Sprint 36',
    targetTurnaroundDays: 4,
    createdAt: '2025-05-10T10:00:00Z',
    updatedAt: '2025-05-11T14:30:00Z',
    clientContact: {
      name: 'Capt. Roger Vance',
      email: 'rvance@aeropulse.aero',
      role: 'Director of Flight Safety',
      avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    },
    assignedLead: DEFAULT_LEAD,
    deliverables: [
      {
        id: 'del-901',
        title: 'Merkle Tree Hash Generation for Checklists',
        description: 'Chain event logs with SHA-256 cryptographic hashes preventing modification.',
        hours: 10,
        category: 'Backend',
      },
      {
        id: 'del-902',
        title: 'Inspector Verification QR & Web Portal',
        description: 'Public verifiable URL for FAA auditors to validate archive hash integrity.',
        hours: 8,
        category: 'Frontend',
      },
      {
        id: 'del-903',
        title: 'Automated Weekly S3 Glacier Archival',
        description: 'Object lock compliance policy preventing deletion for 7 years.',
        hours: 6,
        category: 'QA & DevOps',
      },
    ],
    exclusions: ['Physical microfiche printouts', 'Classified defense avionics telemetry'],
    approvalToken: 'tok_aero_9981e',
    approvalDetails: {
      approvedAt: '2025-05-11T14:30:00Z',
      approvedBy: 'Capt. Roger Vance',
      confirmationCode: 'CF-9410',
    },
  },
  {
    id: 'CR-1051',
    client: 'HyperScale Inc',
    project: 'SaaS Analytics Dashboard',
    title: 'Multi-Tenant SSO via Okta SAML 2.0',
    description: 'Enterprise SSO integration allowing corporate customer organizations to enforce SAML login.',
    rawQuote: '“Enterprise tier prospects are demanding Okta SAML before committing to annual $50k licenses.”',
    channel: 'Portal',
    channelSource: 'Client Portal',
    urgency: 'High',
    status: 'in_progress',
    estimatedHours: 30,
    hourlyRate: 150,
    estimatedCost: 4500,
    targetSprint: 'Sprint 38',
    targetTurnaroundDays: 6,
    createdAt: '2025-05-18T15:20:00Z',
    updatedAt: '2025-05-18T17:00:00Z',
    clientContact: {
      name: 'Julian Hayes',
      email: 'julian@hyperscale.co',
      role: 'Head of Growth',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    },
    assignedLead: DEFAULT_LEAD,
    deliverables: [
      {
        id: 'del-1001',
        title: 'SAML 2.0 Service Provider Endpoint',
        description: 'XML signature validation, metadata endpoint, and certificate rollover support.',
        hours: 12,
        category: 'Backend',
      },
      {
        id: 'del-1002',
        title: 'Admin SSO Configuration & Domain Verification',
        description: 'DNS TXT record verification and IdP metadata file uploader dialog.',
        hours: 10,
        category: 'Frontend',
      },
      {
        id: 'del-1003',
        title: 'SCIM User Provisioning & Deprovisioning',
        description: 'Automated user account creation and role sync when invited in Okta.',
        hours: 8,
        category: 'Backend',
      },
    ],
    exclusions: ['Active Directory on-premise LDAP sync', 'Hardware YubiKey enforcement policy'],
    approvalToken: 'tok_hyper_8812c',
    approvalDetails: {
      approvedAt: '2025-05-18T17:00:00Z',
      approvedBy: 'Julian Hayes',
      confirmationCode: 'CF-9812',
    },
  },
];

